CREATE DATABASE TSQLSERVERBACKUP
ON PRIMARY(
	NAME= Semana13,
	FILENAME='C:\Tsql\Semana13P.mdf',
	SIZE=10,
	MAXSIZE=50,
	FILEGROWTH=15% 
)
LOG ON(
	NAME= Semana13log,
	FILENAME='C:\Tsql\Semana13L.lgf',
	SIZE=5,
	MAXSIZE=30,
	FILEGROWTH=5% 
)
GO

USE [TSQLSERVERBACKUP]
GO

CREATE TABLE ALUMNO
(
	ALUMNOID int identity(1,1) PRIMARY KEY,
	NOMBRE varchar(50) null,
	NOTA float null,
	NIVEL int null
)
GO

INSERT INTO ALUMNO VALUES ('Josemaria', 20.00, 6)
INSERT INTO ALUMNO VALUES ('Ana', 20.00, 7)
INSERT INTO ALUMNO VALUES ('Kevin', 20.00, 7)
INSERT INTO ALUMNO VALUES ('Hillari', 20.00, 8)
INSERT INTO ALUMNO VALUES ('Jacqueline', 20.00, 7)
INSERT INTO ALUMNO VALUES ('Ian', 20.00, 11)

--BACKUP FULL--

BACKUP DATABASE TSQLSERVERBACKUP TO DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_F.bak'
GO

--BACKUP DEFERENCIAL--

INSERT INTO ALUMNO VALUES ('AAA', 20.00, 1)
INSERT INTO ALUMNO VALUES ('BBB', 20.00, 2)
INSERT INTO ALUMNO VALUES ('CCC', 20.00, 3)
INSERT INTO ALUMNO VALUES ('DDD', 20.00, 4)
INSERT INTO ALUMNO VALUES ('EEE', 20.00, 5)

BACKUP DATABASE TSQLSERVERBACKUP TO DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_D1.dif'
WITH DIFFERENTIAL
GO

INSERT INTO ALUMNO VALUES ('FFF', 20.00, 6)
INSERT INTO ALUMNO VALUES ('GGG', 20.00, 7)
INSERT INTO ALUMNO VALUES ('HHH', 20.00, 8)
INSERT INTO ALUMNO VALUES ('III', 20.00, 9)

BACKUP DATABASE TSQLSERVERBACKUP TO DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_D2.dif'
WITH DIFFERENTIAL
GO


--BACKUP TRANSACTIONAL--

INSERT INTO ALUMNO VALUES ('Sthefy', 20.00, 8)
INSERT INTO ALUMNO VALUES ('Francis', 20.00, 7)
INSERT INTO ALUMNO VALUES ('Jean', 20.00, 11)

BACKUP LOG TSQLSERVERBACKUP TO DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_T1.trn'
GO

INSERT INTO ALUMNO VALUES ('Claudia', 20.00, 8)
INSERT INTO ALUMNO VALUES ('Moritz', 20.00, 7)
INSERT INTO ALUMNO VALUES ('Guisela', 20.00, 11)

BACKUP LOG TSQLSERVERBACKUP TO DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_T2.trn'
GO

--RESTAURAR BACKUP FULL--

RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_F.bak' 
GO

--RESTAURAR BACKUP DIFERENCIAL--

RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_F.bak' WITH NORECOVERY
GO
RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_D1.dif'
GO

RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_F.bak' WITH NORECOVERY
GO
RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_D2.dif'
GO


--RESTAURAR BACKUP TRANSACCIONAL--

RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_F.bak' WITH NORECOVERY
GO
RESTORE DATABASE TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_D1.dif' WITH NORECOVERY
GO
RESTORE LOG TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_T1.trn' WITH NORECOVERY
GO
RESTORE LOG TSQLSERVERBACKUP FROM DISK = 'C:\sqlExamen\TSQLSERVERBACKUP_T2.trn' WITH RECOVERY;  
GO